### ISSUE TITLE
Should support testbed search based on testname

### ISSUE THREAD

**Issue by heannig** [ppi-ag/buster-testbed-extension#1]
It's basically the current principle vice versa. 
Problem: accidently renaming a testbed doesn't lead to an error in "strict"-mode. The tests simply aren't executed.

**Comment by HendrikAnnighoefer** [comment]
What I have learned now: it's an advantage to start looking for a test from a testbed. That's because you can have one testbed for multiple tests. Therefore I close this feature-request.
